services:
  configserver:
    image: "ranju9707/configserver:s8"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    #Config server is now exposing liveness and readiness endpoints. Now using Docker compose check
    #whether Config server is in health state or not
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s #Interval of each try should have a difference of 10 secs
      timeout: 5s #Wait of 5 secs for response before giving up
      retries: 10
      start_period: 10s #Start after 10 secs
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: "ranju9707/eurekaserver:s8"
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s #Interval of each try should have a difference of 10 secs
      timeout: 5s #Wait of 5 secs for response before giving up
      retries: 10
      start_period: 10s #Start after 10 secs
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"

  accounts:
    image: "ranju9707/accounts:s8"
    container_name: accounts-ms
    ports:
      - "9001:9001"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  cards:
    image: "ranju9707/cards:s8"
    container_name: cards-ms
    ports:
      - "9002:9002"
    environment:
      SPRING_APPLICATION_NAME: "cards"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  loans:
    image: "ranju9707/loans:s8"
    container_name: loans-ms
    ports:
      - "9003:9003"
    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  loans1:
    image: "ranju9707/loans:s8"
    container_name: loans-ms1
    ports:
      - "9013:9003"
    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  ranju9707:
    driver: bridge