server:
  port: 9001
spring:
  application:
    name: "accounts"
  profiles:
    active: "default"
  datasource:
    url: jdbc:mysql://localhost:3316/accountsdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/" #Here the configserver tells that the microservice or Spring Boot application needs to
    # connect to the config server. The optional tells that if the config server is not available, the application should not fail and run.
    # If properties are super important then remove optional.
#Bydefault Actuator will run on expose all the management related API path. Thus, we need to enable them
#using a property
management:
  endpoints:
    web:
      exposure:
        include: "*" # * means expose all management api. It include refresh related endpoint