services:
  rabbit:
    image: "rabbitmq:4.0-management"
    hostname: "rabbitmq"
    # 2 ports is used as one will be for management of RabbitMQ and for core activity
    ports:
      - "5672:5672"
      - "15672:15672"
    #Health check of RabbitMQ - As config server and other microservices is dependent on RabbitMQ
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: "ranju9707/configserver:s6"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    #Config server is now exposing liveness and readiness endpoints. Now using Docker compose check
    #whether Config server is in health state or not
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s #Interval of each try should have a difference of 10 secs
      timeout: 5s #Wait of 5 secs for response before giving up
      retries: 10
      start_period: 10s #Start after 10 secs
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "ranju9707/accounts:s6" #image_name:tag_name
    container_name: accounts-ms #This avoids giving random name to the container when it is created by image
    ports:
      - "9001:9001" #if multiple port is to be allocated then can add one more using ex. "3001:3001"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: "ranju9707/cards:s6"
    container_name: cards-ms
    ports:
      - "9002:9002"
    environment:
      SPRING_APPLICATION_NAME: "cards"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: "ranju9707/loans:s6"
    container_name: loans-ms
    ports:
      - "9003:9003"
    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  ranju9707:
    driver: bridge