services:
    network-deploy-service:
      networks:
        - ranju9707

    microservice-db-config:
      extends:
        service: network-deploy-service
      image: mysql
      #All this healthcheck command can be received from offical document
      healthcheck:
        test: ["CMD","mysqladmin","ping","-h","localhost"]
        timeout: 10s
        retries: 10
        interval: 10s
        start_period: 10s
      environment:
        MYSQL_ROOT_PASSWORD: root

    #Whenever microservice is created within the Docker compose file,
    #it will extend the microservice-base-config
    microservice-base-config:
      extends:
        service: network-deploy-service
      deploy:
        resources:
          limits:
            memory: 700m

    microservice-configserver-config:
      extends:
        service: microservice-base-config
      #depends_on:
        #configserver:
          #condition: service_healthy
      environment:
        SPRING_PROFILES_ACTIVE: default
        # The hostname given here should not be localhost but the service name which tells how account
        # micorservice can connect with config server.
        # Inside this docker we have a service name for config server i.e. configserver.
        # The prefix should be always configserver.
        SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root