build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank accounts related Production APIs "
  contactDetails:
    name: "Ranju Pillai - Product Owner"
    email: "ranju.pillai@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345