spring:
  application:
    name: "loans"
  profiles:
    active: "default"
  datasource:
    url: jdbc:mysql://localhost:3318/loansdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 9003